//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEleicao.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public int IdCandidato { get; set; }
        public string Nome { get; set; }
        public string Foto { get; set; }
        public int IdTipoCandidato { get; set; }
        public int QuantidadeVotos { get; set; }
    
        public virtual TipoCandidato TipoCandidato { get; set; }
    }
}
