//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEleicao.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class electionsystemEntities : DbContext
    {
        public electionsystemEntities()
            : base("name=electionsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Eleitor> EleitorSet { get; set; }
        public DbSet<TipoCandidato> TipoCandidatoSet { get; set; }
        public DbSet<Candidato> CandidatoSet { get; set; }
        public DbSet<Uev> UevSet { get; set; }
    }
}
