//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEleicao.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCandidato
    {
        public TipoCandidato()
        {
            this.Candidato = new HashSet<Candidato>();
        }
    
        public int IdTipoCandidato { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Candidato> Candidato { get; set; }
    }
}
